### ISSUE TITLE
Всё в одном файле? И хотелось бы побольше документации.

### ISSUE THREAD

**Issue by MentorTutor** [NikitaDolgii/Tank_Project#5]
https://github.com/NikitaDolgii/Tank_Project/blob/4ab3cc7280ddf462b2772719bce05c850da667bd/Tank_Project_4/main.py#L27-L39

**Comment by NikitaDolgii** [comment]
Документацию добавили.

**Comment by MentorTutor** [comment]
Хорошо, спасибо :)
