### ISSUE TITLE
Здесь и далее. Что за числа? Почему именно такие? Нужны комментарии.

### ISSUE THREAD

**Issue by MentorTutor** [NikitaDolgii/Tank_Project#6]
https://github.com/NikitaDolgii/Tank_Project/blob/4ab3cc7280ddf462b2772719bce05c850da667bd/Tank_Project_4/main.py#L76-L88

**Comment by Ostroumov-Alexander** [comment]
Комментарии добавлены.

**Comment by MentorTutor** [comment]
Отлично :)
