### ISSUE TITLE
Здесь и далее. Можно ли как-то оптимизировать код?

### ISSUE THREAD

**Issue by MentorTutor** [NikitaDolgii/Tank_Project#7]
https://github.com/NikitaDolgii/Tank_Project/blob/4ab3cc7280ddf462b2772719bce05c850da667bd/Tank_Project_4/main.py#L171-L183

**Comment by NikitaDolgii** [comment]
Оптимизация возможна,  но не является оправданной, так как кол-во танков не превосходит 2 и изменения усложнят читабельность кода.

**Comment by MentorTutor** [comment]
Хорошо )
