### ISSUE TITLE
Нужно разбить код в несколько файлов. А то тяжело изучать его.

### ISSUE THREAD

**Issue by MentorTutor** [NikitaDolgii/Tank_Project#8]
https://github.com/NikitaDolgii/Tank_Project/blob/4ab3cc7280ddf462b2772719bce05c850da667bd/Tank_Project_4/main.py#L29

**Comment by Ostroumov-Alexander** [comment]
Код разделён.

**Comment by MentorTutor** [comment]
Круто )
