### ISSUE TITLE
Ошибка при выстреле тройным снарядом

### ISSUE THREAD

**Issue by Ostroumov-Alexander** [NikitaDolgii/Tank_Project#9]
В режиме одиночной игры после окончания первой волны возникает ошибка. Если выбрать тройной снаряд и попытаться выстрелить программа вылетает.
TypeError: Bullet.__init__() missing 2 required positional arguments: 'tank_1' and 'bullet_image'

**Comment by NikitaDolgii** [comment]
Ошибку исправил
